### ISSUE TITLE
Rewrite everything in Go

### ISSUE THREAD

**Issue by CalculusEnjoyer** [NikitaMasych/numerical-methods-lab3#1]

**Comment by NikitaMasych** [comment]
### Hello, CalculusEnjoyer! 

It is remarkably great to receive such a feedback, especially from a Java developer😌💂
Judging your expertise in this field by [this](https://github.com/CalculusEnjoyer/Ultimate-Crypto-Rate-Provider) phenomenal project, I with no doubt can state, that there is no more perfect match for this assignment than you!😉

Please, do not let anything prevent your contribution!🤗🤗
